//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Покупатель.
    /// </summary>
    //  *** Start programmer edit section *** (Покупатель CustomAttributes)

    //  *** End programmer edit section *** (Покупатель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПокупательE", new string[] {
            "Навзвание as \'Навзвание\'"})]
    [View("ПокупательL", new string[] {
            "Навзвание as \'Навзвание\'"})]
    public class Покупатель : ICSSoft.STORMNET.DataObject
    {
        
        private string fНавзвание;
        
        //  *** Start programmer edit section *** (Покупатель CustomMembers)

        //  *** End programmer edit section *** (Покупатель CustomMembers)

        
        /// <summary>
        /// Навзвание.
        /// </summary>
        //  *** Start programmer edit section *** (Покупатель.Навзвание CustomAttributes)

        //  *** End programmer edit section *** (Покупатель.Навзвание CustomAttributes)
        [StrLen(255)]
        public virtual string Навзвание
        {
            get
            {
                //  *** Start programmer edit section *** (Покупатель.Навзвание Get start)

                //  *** End programmer edit section *** (Покупатель.Навзвание Get start)
                string result = this.fНавзвание;
                //  *** Start programmer edit section *** (Покупатель.Навзвание Get end)

                //  *** End programmer edit section *** (Покупатель.Навзвание Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Покупатель.Навзвание Set start)

                //  *** End programmer edit section *** (Покупатель.Навзвание Set start)
                this.fНавзвание = value;
                //  *** Start programmer edit section *** (Покупатель.Навзвание Set end)

                //  *** End programmer edit section *** (Покупатель.Навзвание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПокупательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупательE", typeof(IIS.Test.Покупатель));
                }
            }
            
            /// <summary>
            /// "ПокупательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупательL", typeof(IIS.Test.Покупатель));
                }
            }
        }
    }
}
