//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Продажа.
    /// </summary>
    //  *** Start programmer edit section *** (Продажа CustomAttributes)

    //  *** End programmer edit section *** (Продажа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродажаE", new string[] {
            "Дата as \'Дата\'",
            "ОбщаяЦена as \'Общая цена\'",
            "Покупатель as \'Покупатель\'",
            "Покупатель.Навзвание as \'Навзвание\'"})]
    [AssociatedDetailViewAttribute("ПродажаE", "СтрокаПродажи", "СтрокаПродажиE", true, "", "Строка продажи", true, new string[] {
            ""})]
    [View("ПродажаL", new string[] {
            "Дата as \'Дата\'",
            "ОбщаяЦена as \'Общая цена\'",
            "Покупатель.Навзвание as \'Навзвание\'"})]
    public class Продажа : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private double fОбщаяЦена;
        
        private IIS.Test.Покупатель fПокупатель;
        
        private IIS.Test.DetailArrayOfСтрокаПродажи fСтрокаПродажи;
        
        //  *** Start programmer edit section *** (Продажа CustomMembers)

        //  *** End programmer edit section *** (Продажа CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (Продажа.Дата CustomAttributes)

        //  *** End programmer edit section *** (Продажа.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                //  *** Start programmer edit section *** (Продажа.Дата Get start)

                //  *** End programmer edit section *** (Продажа.Дата Get start)
                System.DateTime result = this.fДата;
                //  *** Start programmer edit section *** (Продажа.Дата Get end)

                //  *** End programmer edit section *** (Продажа.Дата Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Продажа.Дата Set start)

                //  *** End programmer edit section *** (Продажа.Дата Set start)
                this.fДата = value;
                //  *** Start programmer edit section *** (Продажа.Дата Set end)

                //  *** End programmer edit section *** (Продажа.Дата Set end)
            }
        }
        
        /// <summary>
        /// ОбщаяЦена.
        /// </summary>
        //  *** Start programmer edit section *** (Продажа.ОбщаяЦена CustomAttributes)

        //  *** End programmer edit section *** (Продажа.ОбщаяЦена CustomAttributes)
        public virtual double ОбщаяЦена
        {
            get
            {
                //  *** Start programmer edit section *** (Продажа.ОбщаяЦена Get start)

                //  *** End programmer edit section *** (Продажа.ОбщаяЦена Get start)
                double result = this.fОбщаяЦена;
                //  *** Start programmer edit section *** (Продажа.ОбщаяЦена Get end)

                //  *** End programmer edit section *** (Продажа.ОбщаяЦена Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Продажа.ОбщаяЦена Set start)

                //  *** End programmer edit section *** (Продажа.ОбщаяЦена Set start)
                this.fОбщаяЦена = value;
                //  *** Start programmer edit section *** (Продажа.ОбщаяЦена Set end)

                //  *** End programmer edit section *** (Продажа.ОбщаяЦена Set end)
            }
        }
        
        /// <summary>
        /// Продажа.
        /// </summary>
        //  *** Start programmer edit section *** (Продажа.Покупатель CustomAttributes)

        //  *** End programmer edit section *** (Продажа.Покупатель CustomAttributes)
        [NotNull()]
        public virtual IIS.Test.Покупатель Покупатель
        {
            get
            {
                //  *** Start programmer edit section *** (Продажа.Покупатель Get start)

                //  *** End programmer edit section *** (Продажа.Покупатель Get start)
                IIS.Test.Покупатель result = this.fПокупатель;
                //  *** Start programmer edit section *** (Продажа.Покупатель Get end)

                //  *** End programmer edit section *** (Продажа.Покупатель Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Продажа.Покупатель Set start)

                //  *** End programmer edit section *** (Продажа.Покупатель Set start)
                this.fПокупатель = value;
                //  *** Start programmer edit section *** (Продажа.Покупатель Set end)

                //  *** End programmer edit section *** (Продажа.Покупатель Set end)
            }
        }
        
        /// <summary>
        /// Продажа.
        /// </summary>
        //  *** Start programmer edit section *** (Продажа.СтрокаПродажи CustomAttributes)

        //  *** End programmer edit section *** (Продажа.СтрокаПродажи CustomAttributes)
        public virtual IIS.Test.DetailArrayOfСтрокаПродажи СтрокаПродажи
        {
            get
            {
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Get start)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Get start)
                if ((this.fСтрокаПродажи == null))
                {
                    this.fСтрокаПродажи = new IIS.Test.DetailArrayOfСтрокаПродажи(this);
                }
                IIS.Test.DetailArrayOfСтрокаПродажи result = this.fСтрокаПродажи;
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Get end)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Set start)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Set start)
                this.fСтрокаПродажи = value;
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Set end)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродажаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажаE", typeof(IIS.Test.Продажа));
                }
            }
            
            /// <summary>
            /// "ПродажаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажаL", typeof(IIS.Test.Продажа));
                }
            }
        }
    }
}
