//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Склад.
    /// </summary>
    //  *** Start programmer edit section *** (Склад CustomAttributes)

    //  *** End programmer edit section *** (Склад CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СкладE", new string[] {
            "Название",
            "Адрес"})]
    [View("СкладL", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'"})]
    public class Склад : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fАдрес;
        
        //  *** Start programmer edit section *** (Склад CustomMembers)

        //  *** End programmer edit section *** (Склад CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Склад.Название CustomAttributes)

        //  *** End programmer edit section *** (Склад.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                //  *** Start programmer edit section *** (Склад.Название Get start)

                //  *** End programmer edit section *** (Склад.Название Get start)
                string result = this.fНазвание;
                //  *** Start programmer edit section *** (Склад.Название Get end)

                //  *** End programmer edit section *** (Склад.Название Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Склад.Название Set start)

                //  *** End programmer edit section *** (Склад.Название Set start)
                this.fНазвание = value;
                //  *** Start programmer edit section *** (Склад.Название Set end)

                //  *** End programmer edit section *** (Склад.Название Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        //  *** Start programmer edit section *** (Склад.Адрес CustomAttributes)

        //  *** End programmer edit section *** (Склад.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                //  *** Start programmer edit section *** (Склад.Адрес Get start)

                //  *** End programmer edit section *** (Склад.Адрес Get start)
                string result = this.fАдрес;
                //  *** Start programmer edit section *** (Склад.Адрес Get end)

                //  *** End programmer edit section *** (Склад.Адрес Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Склад.Адрес Set start)

                //  *** End programmer edit section *** (Склад.Адрес Set start)
                this.fАдрес = value;
                //  *** Start programmer edit section *** (Склад.Адрес Set end)

                //  *** End programmer edit section *** (Склад.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СкладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладE", typeof(IIS.Test.Склад));
                }
            }
            
            /// <summary>
            /// "СкладL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладL", typeof(IIS.Test.Склад));
                }
            }
        }
    }
}
